trigger: 
- main

pool:
    vmImage: ubuntu-latest

variables:
    buildConfiguartion: 'Release'

steps:
- script: dotent build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
