trigger: 
- main

pool:
    vmImage: ubuntu-latest

variables:
    buildConfiguartion: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build the release'
  inputs:
    command: 'build'
    arguments: '--configuration Release'